---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-deployment1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ecommerce
    spec:
      containers:
      - name: ecommerce
        image: narjess6/devops:latest
        ports:
        - containerPort: 9090
