---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-deployment
spec:
  selector:
    matchLabels:
      app: ecommerce
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: ecommerce
    spec:
      containers:
      - name: ecommerce
        image: narjess6/devops:latest
        ports: 
        - containerPort: 9090
