---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-deployment1
spec:
  selector:
    matchLabels:
      app: ecommerce
  replicas: 1
  template:
    metadata:
      labels:
        app: ecommerce
    spec:
      containers:
      - name: ecommerce
        image: narjess6/devops:7.1
        ports:
        - containerPort: 9090
